# This is a basic workflow to help you get started with Actions

name: eslinting

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    - name: yarn install
      run: yarn install
    - name: eslint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: src # only if a different glob is needed, default: src
