name: Typescript Compiler

on:
  push:

  workflow_dispatch:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install
      run: yarn install
    - name: yarn install ts
      run: yarn add typescript
    -name: yarn install ts compiler
      run: yarn add tsc
    - name: tsc
      uses: icrawl/action-tsc@v1